title: Johnathan Croft
author:
  name: Johnathan Croft
  email: croftmjohn@gmail.com
description: >-
  A professional portfolio and blog exploring philosophy, thoughts, and projects.

# --- Deployment Settings ---
# `url` is your main GitHub Pages domain.
url: "https://john-croft.com" # Replace with your GitHub username
# `baseurl` is the name of your repository.
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/

# Social media links
social:
  linkedin: https://www.linkedin.com/in/devjohnathan/
  github: https://github.com/jmcroft7
  substack: https://substack.com/@johncroft1
  goodreads: https://www.goodreads.com/johncroft1
  cv: /assets/documents/resume.pdf
